# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/self-study',
                'doc_host': 'https://khankanz.github.io',
                'git_url': 'https://github.com/khankanz/self-study',
                'lib_path': 'self_study'},
  'syms': {'self_study.core': {'self_study.core.foo': ('core.html#foo', 'self_study/core.py')}}}
